name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: windows-latest  # 切換到使用 Windows runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.202'
        msbuild-version: '17.0.0'

    - name: Build
      run: dotnet build -c Release

    - name: Test
      run: dotnet test -c Release
      
    - name: Clean and Restore
      run: |
       dotnet clean -c Release
       dotnet restore
